---
# tasks file for wit.

- name: Import DNS hostip check from wit.dnstools
  ansible.builtin.include_role:
    name: wit.dnstools
    tasks_from: checkhostip
  when: not (common_skip_dns_check | default(false) | bool)