---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock
  tasks:
    - name: Ensure controller Python deps for Docker modules
      ansible.builtin.pip:
        name:
          - docker==6.1.3
          - molecule-docker==2.0.0
          - requests-unixsocket
          - requests==2.31.0
          - urllib3==2.1.0
        state: present
        extra_args: "--break-system-packages --upgrade --force-reinstall --ignore-installed"
      register: controller_docker_deps
      changed_when: false

    - name: Destroy molecule instance(s)
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
        force_kill: "{{ item.force_kill | default(true) }}"
        docker_host: unix:///var/run/docker.sock
      register: server
      with_items: "{{ molecule_yml.platforms }}"
      
    

