---
dependency:
  name: galaxy
  options:
    requirements-file: collections/requirements.yml
    force: true
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    privileged: true
    command: ""
provisioner:
  name: ansible
  env:
    ALLOW_BROKEN_CONDITIONALS: true
    ANSIBLE_ROLES_PATH: "../../../:/usr/share/ansible/roles:/etc/ansible/roles:/root/.ansible/roles"
    ANSIBLE_DEPRECATION_WARNINGS: "true"
    ANSIBLE_CONFIG: "${MOLECULE_SCENARIO_DIRECTORY}/ansible.cfg"
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
