name: Molecule

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Install pinned deps (if empty, no-op)
          pip install -r ci/requirements.txt || true
          # Ensure required tools are present (respects pins already installed)
          pip install --upgrade \
            "ansible-core>=2.18" \
            "molecule>=6" \
            "molecule-plugins[docker]" \
            docker \
            ansible-lint \
            yamllint

      - name: Install scenario collections
        run: |
          ansible-galaxy collection install -r molecule/default/collections/requirements.yml --force

      - name: Docker diagnostics
        run: |
          docker --version
          docker info

      - name: Pre-pull Molecule base image (with retry)
        run: |
          for i in 1 2 3; do
            docker pull geerlingguy/docker-ubuntu2204-ansible:latest && break || sleep 10
          done

      - name: Run Molecule tests
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "1"
          MOLECULE_DEBUG: "1"
          ANSIBLE_VERBOSITY: "2"
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          molecule --version
          ansible --version
          molecule test
